-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 09:13:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uffsscheduler
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uffsscheduler` ;

-- -----------------------------------------------------
-- Schema uffsscheduler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uffsscheduler` DEFAULT CHARACTER SET utf8 ;
USE `uffsscheduler` ;

-- -----------------------------------------------------
-- Table `uffsscheduler`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uffsscheduler`.`roles` ;

CREATE TABLE IF NOT EXISTS `uffsscheduler`.`roles` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uffsscheduler`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uffsscheduler`.`users` ;

CREATE TABLE IF NOT EXISTS `uffsscheduler`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `enrollment` BIGINT NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `registry_date` DATE NOT NULL,
  `ban_status` TINYINT(1) NOT NULL,
  `user_role_uid` INT NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `enrollment_UNIQUE` (`enrollment` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `users_role_uid_idx` (`user_role_uid` ASC),
  CONSTRAINT `users_role_uid`
    FOREIGN KEY (`user_role_uid`)
    REFERENCES `uffsscheduler`.`roles` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uffsscheduler`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uffsscheduler`.`classes` ;

CREATE TABLE IF NOT EXISTS `uffsscheduler`.`classes` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `year` INT NOT NULL,
  `semester` INT NOT NULL,
  `shift` VARCHAR(20) NOT NULL,
  `period` INT NOT NULL,
  `registry_date` DATE NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uffsscheduler`.`ccrs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uffsscheduler`.`ccrs` ;

CREATE TABLE IF NOT EXISTS `uffsscheduler`.`ccrs` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `registry_date` DATE NOT NULL,
  `class_uid` INT NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `ccrs_class_uid_idx` (`class_uid` ASC),
  CONSTRAINT `ccrs_class_uid`
    FOREIGN KEY (`class_uid`)
    REFERENCES `uffsscheduler`.`classes` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
